services:
  backend:
    build:
      context: ./Talkse-backend/Talkse-backend
      dockerfile: Dockerfile
    container_name: talkse_backend
    ports:
      - "8000:8000"
    env_file:
      - ./Talkse-backend/Talkse-backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_CLERK_PUBLISHABLE_KEY: ${VITE_CLERK_PUBLISHABLE_KEY:-pk_test_d2VhbHRoeS1tdWxsZXQtMjIuY2xlcmsuYWNjb3VudHMuZGV2JA}
    container_name: talkse_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
